#include "ZMET2016.h"
ZMET2016 phys;
namespace zmet {
	const int &run() { return phys.run(); }
	const int &lumi() { return phys.lumi(); }
	const unsigned long long &evt() { return phys.evt(); }
	const int &isData() { return phys.isData(); }
	const bool &evt_passgoodrunlist() { return phys.evt_passgoodrunlist(); }
	const float &evt_scale1fb() { return phys.evt_scale1fb(); }
	const float &evt_xsec() { return phys.evt_xsec(); }
	const float &evt_kfactor() { return phys.evt_kfactor(); }
	const float &evt_filter() { return phys.evt_filter(); }
	const int &evt_nEvts() { return phys.evt_nEvts(); }
	const float &puWeight() { return phys.puWeight(); }
	const int &nVert() { return phys.nVert(); }
	const int &nTrueInt() { return phys.nTrueInt(); }
	const float &rho() { return phys.rho(); }
	const float &rho25() { return phys.rho25(); }
	const float &gen_ht() { return phys.gen_ht(); }
	const int &nBJetTight() { return phys.nBJetTight(); }
	const int &nBJetMedium() { return phys.nBJetMedium(); }
	const int &nBJetLoose() { return phys.nBJetLoose(); }
	const int &nBJetTight_up() { return phys.nBJetTight_up(); }
	const int &nBJetMedium_up() { return phys.nBJetMedium_up(); }
	const int &nBJetLoose_up() { return phys.nBJetLoose_up(); }
	const int &nBJetTight_dn() { return phys.nBJetTight_dn(); }
	const int &nBJetMedium_dn() { return phys.nBJetMedium_dn(); }
	const int &nBJetLoose_dn() { return phys.nBJetLoose_dn(); }
	const int &nMuons10() { return phys.nMuons10(); }
	const int &nElectrons10() { return phys.nElectrons10(); }
	const int &nGammas20() { return phys.nGammas20(); }
	const float &met_pt() { return phys.met_pt(); }
	const float &met_phi() { return phys.met_phi(); }
	const float &met_calo_pt() { return phys.met_calo_pt(); }
	const float &met_calo_phi() { return phys.met_calo_phi(); }
	const float &met_rawPt() { return phys.met_rawPt(); }
	const float &met_rawPhi() { return phys.met_rawPhi(); }
	const float &met_genPt() { return phys.met_genPt(); }
	const float &met_genPhi() { return phys.met_genPhi(); }
	const float &sumet_raw() { return phys.sumet_raw(); }
	const int &Flag_ecalLaserCorrFilter() { return phys.Flag_ecalLaserCorrFilter(); }
	const int &Flag_hcalLaserEventFilter() { return phys.Flag_hcalLaserEventFilter(); }
	const int &Flag_trackingFailureFilter() { return phys.Flag_trackingFailureFilter(); }
	const int &Flag_CSCTightHaloFilter() { return phys.Flag_CSCTightHaloFilter(); }
	const int &Flag_HBHENoiseFilter() { return phys.Flag_HBHENoiseFilter(); }
	const int &Flag_HBHEIsoNoiseFilter() { return phys.Flag_HBHEIsoNoiseFilter(); }
	const int &Flag_CSCTightHalo2015Filter() { return phys.Flag_CSCTightHalo2015Filter(); }
	const int &Flag_EcalDeadCellTriggerPrimitiveFilter() { return phys.Flag_EcalDeadCellTriggerPrimitiveFilter(); }
	const int &Flag_goodVertices() { return phys.Flag_goodVertices(); }
	const int &Flag_eeBadScFilter() { return phys.Flag_eeBadScFilter(); }
	const int &Flag_globalTightHalo2016() { return phys.Flag_globalTightHalo2016(); }
	const int &Flag_badMuonFilter() { return phys.Flag_badMuonFilter(); }
	const int &Flag_badChargedCandidateFilter() { return phys.Flag_badChargedCandidateFilter(); }
	const int &HLT_singleEl() { return phys.HLT_singleEl(); }
	const int &HLT_singleMu() { return phys.HLT_singleMu(); }
	const int &HLT_DoubleEl_noiso() { return phys.HLT_DoubleEl_noiso(); }
	const int &HLT_DoubleEl() { return phys.HLT_DoubleEl(); }
	const int &HLT_DoubleEl_DZ() { return phys.HLT_DoubleEl_DZ(); }
	const int &HLT_DoubleEl_DZ_2() { return phys.HLT_DoubleEl_DZ_2(); }
	const int &HLT_MuEG() { return phys.HLT_MuEG(); }
	const int &HLT_MuEG_2() { return phys.HLT_MuEG_2(); }
	const int &HLT_MuEG_noiso() { return phys.HLT_MuEG_noiso(); }
	const int &HLT_Mu8_EG17() { return phys.HLT_Mu8_EG17(); }
	const int &HLT_Mu8_EG23() { return phys.HLT_Mu8_EG23(); }
	const int &HLT_Mu17_EG12() { return phys.HLT_Mu17_EG12(); }
	const int &HLT_Mu23_EG12() { return phys.HLT_Mu23_EG12(); }
	const int &HLT_Mu23_EG8() { return phys.HLT_Mu23_EG8(); }
	const int &HLT_DoubleMu_noiso() { return phys.HLT_DoubleMu_noiso(); }
	const int &HLT_DoubleMu() { return phys.HLT_DoubleMu(); }
	const int &HLT_DoubleMu_tk() { return phys.HLT_DoubleMu_tk(); }
	const int &HLT_DoubleMu_nonDZ() { return phys.HLT_DoubleMu_nonDZ(); }
	const int &HLT_DoubleMu_tk_nonDZ() { return phys.HLT_DoubleMu_tk_nonDZ(); }
	const int &HLT_Photon22_R9Id90_HE10_IsoM() { return phys.HLT_Photon22_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon30_R9Id90_HE10_IsoM() { return phys.HLT_Photon30_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon36_R9Id90_HE10_IsoM() { return phys.HLT_Photon36_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon50_R9Id90_HE10_IsoM() { return phys.HLT_Photon50_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon75_R9Id90_HE10_IsoM() { return phys.HLT_Photon75_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon90_R9Id90_HE10_IsoM() { return phys.HLT_Photon90_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon120_R9Id90_HE10_IsoM() { return phys.HLT_Photon120_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon165_R9Id90_HE10_IsoM() { return phys.HLT_Photon165_R9Id90_HE10_IsoM(); }
	const int &HLT_Photon165_HE10() { return phys.HLT_Photon165_HE10(); }
	const int &HLT_CaloJet500_NoJetID() { return phys.HLT_CaloJet500_NoJetID(); }
	const int &HLT_ECALHT800_NoJetID() { return phys.HLT_ECALHT800_NoJetID(); }
	const float &dilmass() { return phys.dilmass(); }
	const float &dilpt() { return phys.dilpt(); }
	const float &dRll() { return phys.dRll(); }
	const float &matched_neutralemf() { return phys.matched_neutralemf(); }
	const float &matched_emf() { return phys.matched_emf(); }
	const bool &elveto() { return phys.elveto(); }
	const int &nlep() { return phys.nlep(); }
	const int &nveto_leptons() { return phys.nveto_leptons(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &lep_p4() { return phys.lep_p4(); }
	const vector<float> &lep_pt() { return phys.lep_pt(); }
	const vector<float> &lep_eta() { return phys.lep_eta(); }
	const vector<float> &lep_phi() { return phys.lep_phi(); }
	const vector<float> &lep_mass() { return phys.lep_mass(); }
	const vector<int> &lep_charge() { return phys.lep_charge(); }
	const vector<int> &lep_pdgId() { return phys.lep_pdgId(); }
	const vector<float> &lep_dxy() { return phys.lep_dxy(); }
	const vector<float> &lep_etaSC() { return phys.lep_etaSC(); }
	const vector<float> &lep_dz() { return phys.lep_dz(); }
	const vector<int> &lep_tightId() { return phys.lep_tightId(); }
	const vector<float> &lep_relIso03() { return phys.lep_relIso03(); }
	const vector<float> &lep_relIso03MREA() { return phys.lep_relIso03MREA(); }
	const vector<float> &lep_relIso03MRDB() { return phys.lep_relIso03MRDB(); }
	const vector<float> &lep_relIso03MRNC() { return phys.lep_relIso03MRNC(); }
	const vector<float> &lep_relIso04() { return phys.lep_relIso04(); }
	const vector<int> &lep_mcMatchId() { return phys.lep_mcMatchId(); }
	const vector<int> &lep_lostHits() { return phys.lep_lostHits(); }
	const vector<int> &lep_convVeto() { return phys.lep_convVeto(); }
	const vector<int> &lep_tightCharge() { return phys.lep_tightCharge(); }
	const vector<float> &lep_MVA() { return phys.lep_MVA(); }
	const vector<float> &lep_validfraction() { return phys.lep_validfraction(); }
	const vector<float> &lep_pterr() { return phys.lep_pterr(); }
	const int &nisoTrack_5gev() { return phys.nisoTrack_5gev(); }
	const int &nisoTrack_10gev() { return phys.nisoTrack_10gev(); }
	const int &nisoTrack_lowmt() { return phys.nisoTrack_lowmt(); }
	const int &nisoTrack_himt() { return phys.nisoTrack_himt(); }
	const int &ngamma() { return phys.ngamma(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &gamma_p4() { return phys.gamma_p4(); }
	const vector<float> &gamma_pt() { return phys.gamma_pt(); }
	const vector<float> &gamma_eta() { return phys.gamma_eta(); }
	const vector<float> &gamma_phi() { return phys.gamma_phi(); }
	const vector<float> &gamma_mass() { return phys.gamma_mass(); }
	const vector<int> &gamma_mcMatchId() { return phys.gamma_mcMatchId(); }
	const vector<float> &gamma_genIso() { return phys.gamma_genIso(); }
	const vector<float> &gamma_chHadIso() { return phys.gamma_chHadIso(); }
	const vector<float> &gamma_neuHadIso() { return phys.gamma_neuHadIso(); }
	const vector<float> &gamma_phIso() { return phys.gamma_phIso(); }
	const vector<float> &gamma_sigmaIetaIeta() { return phys.gamma_sigmaIetaIeta(); }
	const vector<float> &gamma_r9() { return phys.gamma_r9(); }
	const vector<float> &gamma_hOverE() { return phys.gamma_hOverE(); }
	const vector<int> &gamma_idCutBased() { return phys.gamma_idCutBased(); }
	const vector<float> &gamma_ecpfclusiso() { return phys.gamma_ecpfclusiso(); }
	const vector<float> &gamma_hcpfclusiso() { return phys.gamma_hcpfclusiso(); }
	const vector<float> &gamma_hollowtkiso03() { return phys.gamma_hollowtkiso03(); }
	const int &ngenPart() { return phys.ngenPart(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &genPart_p4() { return phys.genPart_p4(); }
	const vector<float> &genPart_pt() { return phys.genPart_pt(); }
	const vector<float> &genPart_eta() { return phys.genPart_eta(); }
	const vector<float> &genPart_phi() { return phys.genPart_phi(); }
	const vector<float> &genPart_mass() { return phys.genPart_mass(); }
	const vector<int> &genPart_pdgId() { return phys.genPart_pdgId(); }
	const vector<int> &genPart_status() { return phys.genPart_status(); }
	const vector<float> &genPart_charge() { return phys.genPart_charge(); }
	const vector<int> &genPart_motherId() { return phys.genPart_motherId(); }
	const vector<int> &genPart_grandmaId() { return phys.genPart_grandmaId(); }
	const vector<bool> &genPart_isp6status3() { return phys.genPart_isp6status3(); }
	const int &ngenLep() { return phys.ngenLep(); }
	const vector<float> &genLep_pt() { return phys.genLep_pt(); }
	const vector<float> &genLep_eta() { return phys.genLep_eta(); }
	const vector<float> &genLep_phi() { return phys.genLep_phi(); }
	const vector<float> &genLep_mass() { return phys.genLep_mass(); }
	const vector<int> &genLep_pdgId() { return phys.genLep_pdgId(); }
	const vector<int> &genLep_status() { return phys.genLep_status(); }
	const vector<float> &genLep_charge() { return phys.genLep_charge(); }
	const vector<int> &genLep_sourceId() { return phys.genLep_sourceId(); }
	const vector<bool> &genLep_isp6status3() { return phys.genLep_isp6status3(); }
	const int &ngenTau() { return phys.ngenTau(); }
	const vector<float> &genTau_pt() { return phys.genTau_pt(); }
	const vector<float> &genTau_eta() { return phys.genTau_eta(); }
	const vector<float> &genTau_phi() { return phys.genTau_phi(); }
	const vector<float> &genTau_mass() { return phys.genTau_mass(); }
	const vector<int> &genTau_pdgId() { return phys.genTau_pdgId(); }
	const vector<int> &genTau_status() { return phys.genTau_status(); }
	const vector<float> &genTau_charge() { return phys.genTau_charge(); }
	const vector<int> &genTau_sourceId() { return phys.genTau_sourceId(); }
	const int &ngenLepFromTau() { return phys.ngenLepFromTau(); }
	const vector<float> &genLepFromTau_pt() { return phys.genLepFromTau_pt(); }
	const vector<float> &genLepFromTau_eta() { return phys.genLepFromTau_eta(); }
	const vector<float> &genLepFromTau_phi() { return phys.genLepFromTau_phi(); }
	const vector<float> &genLepFromTau_mass() { return phys.genLepFromTau_mass(); }
	const vector<int> &genLepFromTau_pdgId() { return phys.genLepFromTau_pdgId(); }
	const vector<int> &genLepFromTau_status() { return phys.genLepFromTau_status(); }
	const vector<float> &genLepFromTau_charge() { return phys.genLepFromTau_charge(); }
	const vector<int> &genLepFromTau_sourceId() { return phys.genLepFromTau_sourceId(); }
	const int &njets() { return phys.njets(); }
	const int &njets_up() { return phys.njets_up(); }
	const int &njets_dn() { return phys.njets_dn(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_p4() { return phys.jets_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_medb_p4() { return phys.jets_medb_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_dn_p4() { return phys.jets_dn_p4(); }
	const vector<ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > > &jets_up_p4() { return phys.jets_up_p4(); }
	const vector<float> &jets_csv() { return phys.jets_csv(); }
	const vector<int> &jets_mcFlavour() { return phys.jets_mcFlavour(); }
	const vector<int> &jets_mcHadronFlav() { return phys.jets_mcHadronFlav(); }
	const float &ht() { return phys.ht(); }
	const float &ht_up() { return phys.ht_up(); }
	const float &ht_dn() { return phys.ht_dn(); }
	const float &mt2() { return phys.mt2(); }
	const float &mt2j() { return phys.mt2j(); }
	const float &mt2b() { return phys.mt2b(); }
	const float &mjj() { return phys.mjj(); }
	const float &mbb_csv() { return phys.mbb_csv(); }
	const float &mbb_bpt() { return phys.mbb_bpt(); }
	const float &dphi_jj() { return phys.dphi_jj(); }
	const float &dphi_ll() { return phys.dphi_ll(); }
	const float &sum_mlb() { return phys.sum_mlb(); }
	const float &deta_jj() { return phys.deta_jj(); }
	const float &dR_jj() { return phys.dR_jj(); }
	const float &dphi_metj1() { return phys.dphi_metj1(); }
	const float &dphi_metj2() { return phys.dphi_metj2(); }
	const float &weight_btagsf() { return phys.weight_btagsf(); }
	const float &weight_btagsf_heavy_UP() { return phys.weight_btagsf_heavy_UP(); }
	const float &weight_btagsf_light_UP() { return phys.weight_btagsf_light_UP(); }
	const float &weight_btagsf_heavy_DN() { return phys.weight_btagsf_heavy_DN(); }
	const float &weight_btagsf_light_DN() { return phys.weight_btagsf_light_DN(); }
	const float &chpfcands_0013_pt() { return phys.chpfcands_0013_pt(); }
	const float &chpfcands_1316_pt() { return phys.chpfcands_1316_pt(); }
	const float &chpfcands_1624_pt() { return phys.chpfcands_1624_pt(); }
	const float &chpfcands_2430_pt() { return phys.chpfcands_2430_pt(); }
	const float &chpfcands_30in_pt() { return phys.chpfcands_30in_pt(); }
	const float &phpfcands_0013_pt() { return phys.phpfcands_0013_pt(); }
	const float &phpfcands_1316_pt() { return phys.phpfcands_1316_pt(); }
	const float &phpfcands_1624_pt() { return phys.phpfcands_1624_pt(); }
	const float &phpfcands_2430_pt() { return phys.phpfcands_2430_pt(); }
	const float &phpfcands_30in_pt() { return phys.phpfcands_30in_pt(); }
	const float &nupfcands_0013_pt() { return phys.nupfcands_0013_pt(); }
	const float &nupfcands_1316_pt() { return phys.nupfcands_1316_pt(); }
	const float &nupfcands_1624_pt() { return phys.nupfcands_1624_pt(); }
	const float &nupfcands_2430_pt() { return phys.nupfcands_2430_pt(); }
	const float &nupfcands_30in_pt() { return phys.nupfcands_30in_pt(); }
	const float &chpfcands_0013_sumet() { return phys.chpfcands_0013_sumet(); }
	const float &chpfcands_1316_sumet() { return phys.chpfcands_1316_sumet(); }
	const float &chpfcands_1624_sumet() { return phys.chpfcands_1624_sumet(); }
	const float &chpfcands_2430_sumet() { return phys.chpfcands_2430_sumet(); }
	const float &chpfcands_30in_sumet() { return phys.chpfcands_30in_sumet(); }
	const float &phpfcands_0013_sumet() { return phys.phpfcands_0013_sumet(); }
	const float &phpfcands_1316_sumet() { return phys.phpfcands_1316_sumet(); }
	const float &phpfcands_1624_sumet() { return phys.phpfcands_1624_sumet(); }
	const float &phpfcands_2430_sumet() { return phys.phpfcands_2430_sumet(); }
	const float &phpfcands_30in_sumet() { return phys.phpfcands_30in_sumet(); }
	const float &nupfcands_0013_sumet() { return phys.nupfcands_0013_sumet(); }
	const float &nupfcands_1316_sumet() { return phys.nupfcands_1316_sumet(); }
	const float &nupfcands_1624_sumet() { return phys.nupfcands_1624_sumet(); }
	const float &nupfcands_2430_sumet() { return phys.nupfcands_2430_sumet(); }
	const float &nupfcands_30in_sumet() { return phys.nupfcands_30in_sumet(); }
	const float &chpfcands_0013_phi() { return phys.chpfcands_0013_phi(); }
	const float &chpfcands_1316_phi() { return phys.chpfcands_1316_phi(); }
	const float &chpfcands_1624_phi() { return phys.chpfcands_1624_phi(); }
	const float &chpfcands_2430_phi() { return phys.chpfcands_2430_phi(); }
	const float &chpfcands_30in_phi() { return phys.chpfcands_30in_phi(); }
	const float &phpfcands_0013_phi() { return phys.phpfcands_0013_phi(); }
	const float &phpfcands_1316_phi() { return phys.phpfcands_1316_phi(); }
	const float &phpfcands_1624_phi() { return phys.phpfcands_1624_phi(); }
	const float &phpfcands_2430_phi() { return phys.phpfcands_2430_phi(); }
	const float &phpfcands_30in_phi() { return phys.phpfcands_30in_phi(); }
	const float &nupfcands_0013_phi() { return phys.nupfcands_0013_phi(); }
	const float &nupfcands_1316_phi() { return phys.nupfcands_1316_phi(); }
	const float &nupfcands_1624_phi() { return phys.nupfcands_1624_phi(); }
	const float &nupfcands_2430_phi() { return phys.nupfcands_2430_phi(); }
	const float &nupfcands_30in_phi() { return phys.nupfcands_30in_phi(); }
	const float &met_T1CHS_pt() { return phys.met_T1CHS_pt(); }
	const float &met_T1CHS_phi() { return phys.met_T1CHS_phi(); }
	const float &met_T1CHS_fromCORE_pt() { return phys.met_T1CHS_fromCORE_pt(); }
	const float &met_T1CHS_fromCORE_phi() { return phys.met_T1CHS_fromCORE_phi(); }
	const float &met_T1CHS_miniAOD_CORE_pt() { return phys.met_T1CHS_miniAOD_CORE_pt(); }
	const float &met_T1CHS_miniAOD_CORE_phi() { return phys.met_T1CHS_miniAOD_CORE_phi(); }
	const float &met_T1CHS_miniAOD_CORE_up_pt() { return phys.met_T1CHS_miniAOD_CORE_up_pt(); }
	const float &met_T1CHS_miniAOD_CORE_up_phi() { return phys.met_T1CHS_miniAOD_CORE_up_phi(); }
	const float &met_T1CHS_miniAOD_CORE_dn_pt() { return phys.met_T1CHS_miniAOD_CORE_dn_pt(); }
	const float &met_T1CHS_miniAOD_CORE_dn_phi() { return phys.met_T1CHS_miniAOD_CORE_dn_phi(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep1_p4() { return phys.decayedphoton_lep1_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_lep2_p4() { return phys.decayedphoton_lep2_p4(); }
	const ROOT::Math::LorentzVector<ROOT::Math::PxPyPzE4D<float> > &decayedphoton_bosn_p4() { return phys.decayedphoton_bosn_p4(); }
	const float &decayedphoton_mt2() { return phys.decayedphoton_mt2(); }
	const int &hyp_type() { return phys.hyp_type(); }
	const int &evt_type() { return phys.evt_type(); }
	const int &mass_gluino() { return phys.mass_gluino(); }
	const int &mass_LSP() { return phys.mass_LSP(); }
	const float &isrboost() { return phys.isrboost(); }
	const int &isr_njets() { return phys.isr_njets(); }
	const float &isr_weight() { return phys.isr_weight(); }
	const float &isr_unc() { return phys.isr_unc(); }
	const vector<float> &weightsf_lepid() { return phys.weightsf_lepid(); }
	const vector<float> &weightsf_lepiso() { return phys.weightsf_lepiso(); }
	const vector<float> &weightsf_lepip() { return phys.weightsf_lepip(); }
	const vector<float> &weightsf_lepreco() { return phys.weightsf_lepreco(); }
	const vector<float> &weightsf_lepid_FS() { return phys.weightsf_lepid_FS(); }
	const vector<float> &weightsf_lepiso_FS() { return phys.weightsf_lepiso_FS(); }
	const vector<float> &weightsf_lepip_FS() { return phys.weightsf_lepip_FS(); }
}
